
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUMERO RESTA SUMAexpresion : expresion SUMA termino\n                 | expresion RESTA termino\n                 | terminotermino : NUMERO'
    
_lr_action_items = {'NUMERO':([0,4,5,],[3,3,3,]),'$end':([1,2,3,6,7,],[0,-3,-4,-1,-2,]),'SUMA':([1,2,3,6,7,],[4,-3,-4,-1,-2,]),'RESTA':([1,2,3,6,7,],[5,-3,-4,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'termino':([0,4,5,],[2,6,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> expresion SUMA termino','expresion',3,'p_expresion_suma_resta','main.py',29),
  ('expresion -> expresion RESTA termino','expresion',3,'p_expresion_suma_resta','main.py',30),
  ('expresion -> termino','expresion',1,'p_expresion_suma_resta','main.py',31),
  ('termino -> NUMERO','termino',1,'p_termino_numero','main.py',41),
]
